version: '3.9'

services:
  exthree_pgdb:
    image: postgres:latest
    container_name: exthree_pgdb
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: exthree_pgdb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  exthree_app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exthree_app
    depends_on:
      - exthree_pgdb
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    restart: always

volumes:
  pgdata:
    driver: local
